import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';

const AddQuestion = () => {
  const { user } = useAuth();
  const [form, setForm] = useState({
    title: '',
    description: '',
    subject: '',
    questionType: 'MCQ',
    options: ['', '', '', ''],
    correctAnswer: '',
    marks: 2,
    difficulty: 'Easy',
    bloomLevel: 'Remember',
  });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [generatingAI, setGeneratingAI] = useState(false);
  const [customAIInstructions, setCustomAIInstructions] = useState('');
  const [recentQuestions, setRecentQuestions] = useState([]);
  const [checklist, setChecklist] = useState({
    plausible: false,
    unambiguous: false,
    syntax: false,
    marks: false,
    verbs: false
  });

  const fetchRecentQuestions = async () => {
    try {
      const { data } = await api.get('/questions');
      const sorted = (data.questions || [])
        .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
        .slice(0, 5);
      setRecentQuestions(sorted);
    } catch (err) {
      console.error("Could not load recent submissions:", err);
    }
  };

  useEffect(() => {
    fetchRecentQuestions();
  }, []);

  const handleAIGenerate = async () => {
    if (!form.subject) {
      setError('Please enter a Subject first so the AI has context.');
      return;
    }
    if (!aiPrompt) {
      setError('Please enter an AI prompt or topic (e.g. "React Hooks").');
      return;
    }

    setError('');
    setSuccess('');
    setGeneratingAI(true);

    try {
      const { data } = await api.post('/questions/generate-ai', {
        subject: form.subject,
        topicPrompt: aiPrompt,
        questionType: form.questionType,
        difficulty: form.difficulty,
        bloomLevel: form.bloomLevel,
        customInstructions: customAIInstructions,
      });

      setForm({
        ...form,
        title: data.title || '',
        description: data.description || '',
        options: data.options?.length ? [...data.options] : ['', '', '', ''],
        correctAnswer: data.correctAnswer || '',
      });
      setSuccess('Question generated by AI successfully! You can review details below.');
    } catch (err) {
      setError(err.response?.data?.message || 'AI Generation failed. Check key config or try fallback simulation.');
    } finally {
      setGeneratingAI(false);
    }
  };

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleOptionChange = (index, value) => {
    const updated = [...form.options];
    updated[index] = value;
    setForm({ ...form, options: updated });
  };

  const toggleChecklist = (key) => {
    setChecklist({ ...checklist, [key]: !checklist[key] });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setLoading(true);

    try {
      const payload = { ...form, marks: Number(form.marks) };
      if (form.questionType !== 'MCQ') {
        delete payload.options;
      } else {
        payload.options = form.options.filter((o) => o.trim() !== '');
      }

      await api.post('/questions', payload);
      setSuccess('Question added and sent for approval.');
      setForm({
        title: '',
        description: '',
        subject: form.subject, // keep subject for faster bulk entry
        questionType: 'MCQ',
        options: ['', '', '', ''],
        correctAnswer: '',
        marks: 2,
        difficulty: 'Easy',
        bloomLevel: 'Remember',
      });
      setChecklist({
        plausible: false,
        unambiguous: false,
        syntax: false,
        marks: false,
        verbs: false
      });
      fetchRecentQuestions(); // reload log immediately
    } catch (err) {
      setError(err.response?.data?.message || 'Could not add question.');
    } finally {
      setLoading(false);
    }
  };

  const getActiveStream = () => {
    const dept = (user?.department?.name || user?.department || '').toString().toLowerCase();
    if (dept.includes('pharm') || dept.includes('med')) {
      return 'Pharmacy';
    } else if (dept.includes('bus') || dept.includes('comm') || dept.includes('mgt') || dept.includes('finance') || dept.includes('eco')) {
      return 'Business Studies';
    } else if (dept.includes('comp') || dept.includes('cse') || dept.includes('it') || dept.includes('software')) {
      return 'Computer Science';
    }
    return 'General';
  };

  const getSuggestedSubjects = () => {
    const stream = getActiveStream();
    if (stream === 'Pharmacy') {
      return ["Pharmacology", "Pharmaceutics", "Medicinal Chemistry", "Clinical Pharmacy"];
    } else if (stream === 'Business Studies') {
      return ["Financial Accounting", "Business Management", "Marketing Strategy", "Corporate Finance"];
    } else if (stream === 'Computer Science') {
      return ["MERN Stack", "Python Programming", "Database Management", "Data Structures"];
    }
    return ["Engineering Mathematics", "Technical Writing", "Professional Ethics", "Environmental Sciences"];
  };

  const getSuggestedTopics = () => {
    const sub = (form.subject || '').toLowerCase();
    
    // Check Computer Science
    if (sub.includes('mern') || sub.includes('react') || sub.includes('node') || sub.includes('web') || sub.includes('js')) {
      return ["Virtual DOM", "React Hooks", "Redux State", "Express Middleware", "JWT Authentication", "MongoDB Aggregation", "REST APIs"];
    } else if (sub.includes('python') || sub.includes('ml') || sub.includes('numpy') || sub.includes('pandas')) {
      return ["List Comprehensions", "Decorators", "Generators", "Pandas DataFrames", "Numpy Arrays", "Multithreading", "Object-Oriented Python"];
    } else if (sub.includes('db') || sub.includes('sql') || sub.includes('data') || sub.includes('mongo')) {
      return ["Inner vs Outer Joins", "Normalization (1NF-3NF)", "Indexes & Performance", "ACID Properties", "Foreign Keys", "Subqueries"];
    }

    // Check Pharmacy
    else if (sub.includes('pharmacol')) {
      return ["Pharmacokinetics", "Receptor Agonists", "Beta Blockers", "Drug Half-life", "Autonomic Nervous System", "Drug Clearance"];
    } else if (sub.includes('pharmaceut')) {
      return ["Tablet Formulation", "Bioavailability", "Suspensions & Emulsions", "Sterilization Methods", "Controlled Release Systems"];
    } else if (sub.includes('chem')) {
      return ["Structure-Activity Relationship (SAR)", "Prodrugs Design", "Enzyme Inhibitors", "Alkylating Agents", "Bioisosterism in Drugs"];
    }

    // Check Business
    else if (sub.includes('acc') || sub.includes('ledger') || sub.includes('sheet')) {
      return ["Balance Sheets", "Double-Entry Ledger", "Depreciation Methods", "Revenue Recognition", "Cash Flow Statements", "Trial Balance"];
    } else if (sub.includes('manage') || sub.includes('strategy') || sub.includes('swot') || sub.includes('market')) {
      return ["Maslow Hierarchy", "SWOT Analysis", "Product Life Cycle", "4Ps of Marketing Strategy", "Market Segmentation", "Organizational Structures"];
    } else if (sub.includes('finance') || sub.includes('money') || sub.includes('cost')) {
      return ["Time Value of Money", "Capital Budgeting", "Working Capital Cycle", "Opportunity Cost", "Supply & Demand", "Corporate Taxation"];
    }

    // Default general suggestions based on stream
    const stream = getActiveStream();
    if (stream === 'Pharmacy') {
      return ["Dosage Forms", "Clinical Trials", "Drug Interactions", "Toxicology", "Pharmacopeia Standards"];
    } else if (stream === 'Business Studies') {
      return ["Supply & Demand curves", "Capital Budgeting principles", "SWOT matrix analysis", "Time Value of Money (PV/FV)"];
    } else if (stream === 'Computer Science') {
      return ["OOP Principles", "Recursion", "Binary Search Trees", "Sorting Algorithms", "Rest API Design"];
    }
    return ["Linear Algebra", "Calculus Derivatives", "Technical Report Structure", "Intellectual Property Rights", "Climate Change Mitigation"];
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, width: '100%' }}>
      {/* Page Header */}
      <div className="page-header" style={{ margin: 0 }}>
        <h1 style={{ fontSize: 24, fontWeight: 800 }}>Add Question</h1>
        <p>New questions go to "Pending" status until an HOD approves them.</p>
      </div>

      {/* Main Responsive Grid Layout */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: 24, alignItems: 'start', width: '100%' }}>
        
        {/* Left Column: Input Form & AI Panel */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
          
          {/* AI Assistant Card */}
          <div className="card" style={{ borderLeft: '4px solid #a855f7', background: 'linear-gradient(to right, var(--color-surface), var(--color-primary-light))', padding: 20 }}>
            <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
              <span>✨</span> AI Question Assistant ({getActiveStream()} Stream)
            </div>
            <p style={{ fontSize: 13, color: 'var(--color-text-muted)', marginBottom: 14 }}>
              Enter parameters below and click generate to auto-fill the form details.
            </p>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div className="form-row" style={{ gridTemplateColumns: '1fr 1fr', gap: 14, marginBottom: 0 }}>
                <div className="form-group" style={{ margin: 0 }}>
                  <label style={{ fontWeight: 600 }}>Subject</label>
                  <input
                    className="form-control"
                    name="subject"
                    value={form.subject}
                    onChange={handleChange}
                    placeholder="e.g. Pharmacology, Finance, MERN..."
                    required
                  />
                  {/* Subject Suggestions */}
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginTop: 6 }}>
                    {getSuggestedSubjects().map(subj => (
                      <button
                        key={subj}
                        type="button"
                        onClick={() => setForm({ ...form, subject: subj })}
                        style={{
                          background: 'rgba(255, 255, 255, 0.6)',
                          border: '1px solid var(--color-border)',
                          padding: '3px 8px',
                          borderRadius: 8,
                          fontSize: 10,
                          fontWeight: 600,
                          cursor: 'pointer',
                          color: 'var(--color-text)',
                          transition: 'all 0.15s'
                        }}
                        onMouseOver={(e) => {
                          e.currentTarget.style.borderColor = '#a855f7';
                          e.currentTarget.style.background = '#faf5ff';
                        }}
                        onMouseOut={(e) => {
                          e.currentTarget.style.borderColor = 'var(--color-border)';
                          e.currentTarget.style.background = 'rgba(255, 255, 255, 0.6)';
                        }}
                      >
                        {subj}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="form-group" style={{ margin: 0 }}>
                  <label style={{ fontWeight: 600 }}>Concept / Topic Prompt</label>
                  <input
                    className="form-control"
                    value={aiPrompt}
                    onChange={(e) => setAiPrompt(e.target.value)}
                    placeholder="e.g. Pharmacokinetics, balance sheets..."
                    required
                  />
                </div>
              </div>

              {/* Type, Difficulty, Bloom Level inside AI card */}
              <div className="form-row" style={{ gridTemplateColumns: '1fr 1fr 1fr', gap: 14, marginBottom: 0 }}>
                <div className="form-group" style={{ margin: 0 }}>
                  <label style={{ fontWeight: 600 }}>Question Type</label>
                  <select className="form-control" name="questionType" value={form.questionType} onChange={handleChange}>
                    <option value="MCQ">MCQ</option>
                    <option value="TrueFalse">True / False</option>
                    <option value="ShortAnswer">Short Answer</option>
                    <option value="LongAnswer">Long Answer</option>
                    <option value="CaseStudy">Case Study</option>
                    <option value="Programming">Programming</option>
                  </select>
                </div>
                <div className="form-group" style={{ margin: 0 }}>
                  <label style={{ fontWeight: 600 }}>Difficulty</label>
                  <select className="form-control" name="difficulty" value={form.difficulty} onChange={handleChange}>
                    <option value="Easy">Easy</option>
                    <option value="Medium">Medium</option>
                    <option value="Hard">Hard</option>
                  </select>
                </div>
                <div className="form-group" style={{ margin: 0 }}>
                  <label style={{ fontWeight: 600 }}>Bloom's Level</label>
                  <select className="form-control" name="bloomLevel" value={form.bloomLevel} onChange={handleChange}>
                    <option value="Remember">Remember</option>
                    <option value="Understand">Understand</option>
                    <option value="Apply">Apply</option>
                    <option value="Analyze">Analyze</option>
                    <option value="Evaluate">Evaluate</option>
                    <option value="Create">Create</option>
                  </select>
                </div>
              </div>

              {/* Custom Command text input */}
              <div className="form-group" style={{ margin: 0 }}>
                <label style={{ fontWeight: 600 }}>Custom Command / Instructions to AI (optional)</label>
                <input
                  className="form-control"
                  value={customAIInstructions}
                  onChange={(e) => setCustomAIInstructions(e.target.value)}
                  placeholder="e.g. Include code block, make it tricky, add specific answers..."
                />
              </div>

              <button
                type="button"
                className="btn"
                style={{
                  background: 'linear-gradient(135deg, #6366f1, #a855f7)',
                  color: 'white',
                  border: 'none',
                  fontWeight: 600,
                  padding: '10px 16px',
                  borderRadius: '6px',
                  cursor: 'pointer',
                  transition: 'opacity 0.2s',
                  marginTop: 4
                }}
                onClick={handleAIGenerate}
                disabled={generatingAI}
              >
                {generatingAI ? 'Generating question details...' : 'Generate with AI ✨'}
              </button>
            </div>
          </div>

          {/* Form details card */}
          <div className="card" style={{ padding: 20 }}>
            {error && <div className="error-banner" style={{ marginBottom: 14 }}>{error}</div>}
            {success && <div className="success-banner" style={{ marginBottom: 14 }}>{success}</div>}

            <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              <div className="form-group">
                <label style={{ fontWeight: 600 }}>Question Title / Text</label>
                <textarea
                  className="form-control"
                  name="title"
                  value={form.title}
                  onChange={handleChange}
                  placeholder="Explain the Virtual DOM in React..."
                  style={{ minHeight: 70 }}
                  required
                />
              </div>

              <div className="form-group">
                <label style={{ fontWeight: 600 }}>Description (optional)</label>
                <textarea
                  className="form-control"
                  name="description"
                  value={form.description}
                  onChange={handleChange}
                  placeholder="Any extra context, code snippets or instructions..."
                  style={{ minHeight: 60 }}
                />
              </div>

              {form.questionType === 'MCQ' && (
                <div className="form-group" style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <label style={{ fontWeight: 600 }}>Options</label>
                  {form.options.map((opt, i) => (
                    <input
                      key={i}
                      className="form-control"
                      value={opt}
                      onChange={(e) => handleOptionChange(i, e.target.value)}
                      placeholder={`Option ${i + 1}`}
                      required={form.questionType === 'MCQ'}
                    />
                  ))}
                </div>
              )}

              <div className="form-group">
                <label style={{ fontWeight: 600 }}>Correct Answer</label>
                <input
                  className="form-control"
                  name="correctAnswer"
                  value={form.correctAnswer}
                  onChange={handleChange}
                  placeholder="e.g. useState"
                />
              </div>

              <div className="form-row" style={{ gridTemplateColumns: '1fr 1fr', gap: 14 }}>
                <div className="form-group">
                  <label style={{ fontWeight: 600 }}>Marks</label>
                  <input
                    type="number"
                    className="form-control"
                    name="marks"
                    value={form.marks}
                    onChange={handleChange}
                    min={1}
                    required
                  />
                </div>
                <div className="form-group">
                  <label style={{ fontWeight: 600 }}>Difficulty</label>
                  <select className="form-control" name="difficulty" value={form.difficulty} onChange={handleChange}>
                    <option value="Easy">Easy</option>
                    <option value="Medium">Medium</option>
                    <option value="Hard">Hard</option>
                  </select>
                </div>
              </div>

              <div className="form-group">
                <label style={{ fontWeight: 600 }}>Bloom's Taxonomy Level</label>
                <select className="form-control" name="bloomLevel" value={form.bloomLevel} onChange={handleChange}>
                  <option value="Remember">Remember</option>
                  <option value="Understand">Understand</option>
                  <option value="Apply">Apply</option>
                  <option value="Analyze">Analyze</option>
                  <option value="Evaluate">Evaluate</option>
                  <option value="Create">Create</option>
                </select>
              </div>

              <button type="submit" className="btn btn-primary" disabled={loading} style={{ alignSelf: 'flex-start', padding: '10px 24px', fontWeight: 600 }}>
                {loading ? 'Saving...' : 'Add Question'}
              </button>
            </form>
          </div>
        </div>

        {/* Right Column: Live Rendering Preview & Guides */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20, position: 'sticky', top: 20 }}>
          
          {/* Question Live Preview Card */}
          <div className="card" style={{ borderLeft: '4px solid #10b981', padding: 20 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
              <span style={{ fontWeight: 700, fontSize: 13, textTransform: 'uppercase', color: 'var(--color-text-muted)', letterSpacing: '0.05em' }}>
                👀 Question Live Preview
              </span>
              <span className={`badge badge-${form.difficulty?.toLowerCase()}`}>
                {form.difficulty}
              </span>
            </div>

            <div style={{ background: 'var(--color-bg)', padding: 16, borderRadius: 8, border: '1px solid var(--color-border)', minHeight: 180, display: 'flex', flexDirection: 'column', gap: 10 }}>
              {/* Question statement */}
              <div style={{ fontWeight: 600, fontSize: 14, color: 'var(--color-text)', wordBreak: 'break-word', whiteSpace: 'pre-wrap', lineHeight: 1.4 }}>
                {form.title ? form.title : <span style={{ color: 'var(--color-text-muted)', fontStyle: 'italic' }}>Your question title will appear here as you type...</span>}
              </div>

              {/* Description */}
              {form.description && (
                <div style={{ fontSize: 12, color: 'var(--color-text-muted)', whiteSpace: 'pre-wrap', fontStyle: 'italic', borderLeft: '2px solid var(--color-border)', paddingLeft: 8, marginTop: 4 }}>
                  {form.description}
                </div>
              )}

              {/* MCQ Options list */}
              {form.questionType === 'MCQ' && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 8 }}>
                  {form.options.map((opt, i) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13 }}>
                      <span style={{ background: 'var(--color-border)', borderRadius: '50%', width: 22, height: 22, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 700 }}>
                        {String.fromCharCode(65 + i)}
                      </span>
                      <span style={{ color: 'var(--color-text)' }}>
                        {opt ? opt : <span style={{ color: 'var(--color-text-muted)', fontStyle: 'italic' }}>Option {i + 1} empty</span>}
                      </span>
                    </div>
                  ))}
                </div>
              )}

              {/* Correct Answer badge */}
              {form.correctAnswer && (
                <div style={{ marginTop: 12, paddingTop: 10, borderTop: '1px dashed var(--color-border)', fontSize: 12 }}>
                  <span style={{ color: 'var(--color-success)', fontWeight: 700 }}>✔️ Correct Answer:</span>{' '}
                  <span style={{ color: 'var(--color-text-muted)' }}>{form.correctAnswer}</span>
                </div>
              )}
            </div>

            {/* Live details summary bar */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 14, fontSize: 11, color: 'var(--color-text-muted)' }}>
              <span>Subject: <strong>{form.subject || 'Not specified'}</strong></span>
              <span>Marks: <strong>{form.marks}</strong></span>
              <span>Bloom: <strong>{form.bloomLevel}</strong></span>
            </div>
          </div>

          {/* Dynamic Topic Suggestions Card */}
          <div className="card" style={{ padding: 18, borderLeft: '4px solid #f59e0b' }}>
            <div style={{ fontWeight: 700, fontSize: 14, color: 'var(--color-text)', marginBottom: 8 }}>
              💡 Popular Topic Ideas ({form.subject || "General"})
            </div>
            <p style={{ fontSize: 11, color: 'var(--color-text-muted)', marginBottom: 10 }}>
              Click any topic to set the concept prompt:
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
              {getSuggestedTopics().map((topic) => (
                <button
                  key={topic}
                  type="button"
                  onClick={() => setAiPrompt(topic)}
                  style={{
                    background: 'var(--color-bg)',
                    border: '1px solid var(--color-border)',
                    padding: '4px 8px',
                    borderRadius: 12,
                    fontSize: 11,
                    cursor: 'pointer',
                    color: 'var(--color-text)',
                    transition: 'all 0.15s ease'
                  }}
                  onMouseOver={(e) => {
                    e.currentTarget.style.borderColor = '#f59e0b';
                    e.currentTarget.style.background = '#fef3c7';
                  }}
                  onMouseOut={(e) => {
                    e.currentTarget.style.borderColor = 'var(--color-border)';
                    e.currentTarget.style.background = 'var(--color-bg)';
                  }}
                >
                  {topic}
                </button>
              ))}
            </div>
          </div>

          {/* Question Quality Audit Checklist */}
          <div className="card" style={{ padding: 18, borderLeft: '4px solid #3b82f6' }}>
            <div style={{ fontWeight: 700, fontSize: 14, color: 'var(--color-text)', marginBottom: 10 }}>
              ✅ Quality Standards Audit
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <label style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 12, cursor: 'pointer', color: 'var(--color-text)' }}>
                <input type="checkbox" checked={checklist.plausible} onChange={() => toggleChecklist('plausible')} style={{ marginTop: 2 }} />
                <span style={{ textDecoration: checklist.plausible ? 'line-through' : 'none', color: checklist.plausible ? 'var(--color-text-muted)' : 'inherit' }}>
                  Options are distinct and plausible.
                </span>
              </label>
              <label style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 12, cursor: 'pointer', color: 'var(--color-text)' }}>
                <input type="checkbox" checked={checklist.unambiguous} onChange={() => toggleChecklist('unambiguous')} style={{ marginTop: 2 }} />
                <span style={{ textDecoration: checklist.unambiguous ? 'line-through' : 'none', color: checklist.unambiguous ? 'var(--color-text-muted)' : 'inherit' }}>
                  Correct answer is verified and clear.
                </span>
              </label>
              <label style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 12, cursor: 'pointer', color: 'var(--color-text)' }}>
                <input type="checkbox" checked={checklist.syntax} onChange={() => toggleChecklist('syntax')} style={{ marginTop: 2 }} />
                <span style={{ textDecoration: checklist.syntax ? 'line-through' : 'none', color: checklist.syntax ? 'var(--color-text-muted)' : 'inherit' }}>
                  Question has no typos or code errors.
                </span>
              </label>
              <label style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 12, cursor: 'pointer', color: 'var(--color-text)' }}>
                <input type="checkbox" checked={checklist.marks} onChange={() => toggleChecklist('marks')} style={{ marginTop: 2 }} />
                <span style={{ textDecoration: checklist.marks ? 'line-through' : 'none', color: checklist.marks ? 'var(--color-text-muted)' : 'inherit' }}>
                  Marks correspond with taxonomy level.
                </span>
              </label>
              <label style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 12, cursor: 'pointer', color: 'var(--color-text)' }}>
                <input type="checkbox" checked={checklist.verbs} onChange={() => toggleChecklist('verbs')} style={{ marginTop: 2 }} />
                <span style={{ textDecoration: checklist.verbs ? 'line-through' : 'none', color: checklist.verbs ? 'var(--color-text-muted)' : 'inherit' }}>
                  Active verbs match Bloom's taxonomy.
                </span>
              </label>
            </div>
          </div>

          {/* Bloom's Taxonomy Level Guide */}
          <div className="card" style={{ borderLeft: '4px solid #6366f1', padding: 18 }}>
            <div style={{ fontWeight: 700, fontSize: 14, color: 'var(--color-text)', marginBottom: 10, display: 'flex', alignItems: 'center', gap: 6 }}>
              <span>🎓</span> Taxonomy Level Guidelines
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10, fontSize: 12, color: 'var(--color-text-muted)', lineHeight: 1.4 }}>
              <div>
                <strong>Remember & Understand:</strong> Identify keywords, definitions, basic explanations.
              </div>
              <div>
                <strong>Apply & Analyze:</strong> Solve scenarios, code blocks, comparative evaluations.
              </div>
              <div>
                <strong>Evaluate & Create:</strong> Diagnose performance bottlenecks, system architectural designs.
              </div>
            </div>
          </div>

        </div>

      </div>

      {/* Full-width bottom section: Recent Submissions Log */}
      <div className="card" style={{ marginTop: 12, padding: 0, overflow: 'hidden' }}>
        <div style={{ padding: '18px 20px 14px', borderBottom: '1px solid var(--color-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
          <div>
            <div style={{ fontWeight: 700, fontSize: 15, display: 'flex', alignItems: 'center', gap: 6, color: 'var(--color-text)' }}>
              <span>⏱️</span> Your Recent Submissions
            </div>
            <p style={{ fontSize: 12, color: 'var(--color-text-muted)', margin: '4px 0 0' }}>
              Track the approval status of your recently created questions.
            </p>
          </div>
          <button className="btn btn-secondary btn-sm" onClick={fetchRecentQuestions} style={{ padding: '6px 12px', fontSize: 12 }}>
            🔄 Refresh Log
          </button>
        </div>

        {recentQuestions.length === 0 ? (
          <p style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)', fontSize: 13, margin: 0 }}>
            No recent submissions found. Use the forms above to add new questions!
          </p>
        ) : (
          <div className="table-wrap">
            <table className="data-table" style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: 'var(--color-bg)', borderBottom: '1px solid var(--color-border)' }}>
                  <th style={{ padding: '12px 18px', textAlign: 'left', fontSize: 12, color: 'var(--color-text-muted)' }}>Question Statement</th>
                  <th style={{ padding: '12px 18px', textAlign: 'left', fontSize: 12, color: 'var(--color-text-muted)' }}>Subject</th>
                  <th style={{ padding: '12px 18px', textAlign: 'left', fontSize: 12, color: 'var(--color-text-muted)' }}>Type</th>
                  <th style={{ padding: '12px 18px', textAlign: 'left', fontSize: 12, color: 'var(--color-text-muted)' }}>Marks</th>
                  <th style={{ padding: '12px 18px', textAlign: 'left', fontSize: 12, color: 'var(--color-text-muted)' }}>Difficulty</th>
                  <th style={{ padding: '12px 18px', textAlign: 'left', fontSize: 12, color: 'var(--color-text-muted)' }}>Status</th>
                </tr>
              </thead>
              <tbody>
                {recentQuestions.map((q) => (
                  <tr key={q._id} style={{ borderBottom: '1px solid var(--color-border)' }} className="table-row-hover">
                    <td style={{ padding: '12px 18px', fontSize: 13, fontWeight: 500, color: 'var(--color-text)', maxWidth: 450, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {q.title}
                    </td>
                    <td style={{ padding: '12px 18px', fontSize: 12, color: 'var(--color-text-muted)' }}>{q.subject}</td>
                    <td style={{ padding: '12px 18px', fontSize: 12, color: 'var(--color-text-muted)' }}>{q.questionType}</td>
                    <td style={{ padding: '12px 18px', fontSize: 12, fontWeight: 600, color: 'var(--color-text)' }}>{q.marks}</td>
                    <td style={{ padding: '12px 18px' }}>
                      <span className={`badge badge-${q.difficulty?.toLowerCase()}`} style={{ fontSize: 11 }}>{q.difficulty}</span>
                    </td>
                    <td style={{ padding: '12px 18px' }}>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                        <span className={`badge badge-${q.status?.toLowerCase()}`} style={{ fontSize: 11, alignSelf: 'flex-start' }}>{q.status}</span>
                        {q.status === 'Rejected' && q.rejectionReason && (
                          <span style={{ fontSize: 10, color: 'var(--color-danger)', fontStyle: 'italic' }}>Reason: {q.rejectionReason}</span>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

    </div>
  );
};

export default AddQuestion;