import { useEffect, useState } from 'react';
import api from '../utils/api';

const Approvals = () => {
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [rejectingId, setRejectingId] = useState(null);
  const [reason, setReason] = useState('');

  const fetchPending = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/approvals/pending');
      setQuestions(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPending();
  }, []);

  const handleApprove = async (id) => {
    try {
      await api.put(`/approvals/${id}/approve`);
      setQuestions(questions.filter((q) => q._id !== id));
    } catch (err) {
      alert(err.response?.data?.message || 'Could not approve question.');
    }
  };

  const handleReject = async (id) => {
    try {
      await api.put(`/approvals/${id}/reject`, { reason });
      setQuestions(questions.filter((q) => q._id !== id));
      setRejectingId(null);
      setReason('');
    } catch (err) {
      alert(err.response?.data?.message || 'Could not reject question.');
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, width: '100%' }}>
      {/* Page Header */}
      <div className="page-header" style={{ margin: 0 }}>
        <h1 style={{ fontSize: 24, fontWeight: 800 }}>Pending Approvals</h1>
        <p>Review questions submitted by faculty or auto-generated by AI before they enter the active question bank.</p>
      </div>

      {/* Stats Summary Panel */}
      <div className="card" style={{ borderLeft: '4px solid var(--color-warning)', background: 'linear-gradient(to right, var(--color-surface), var(--color-primary-light))', padding: '16px 20px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
          <div>
            <div style={{ fontWeight: 700, fontSize: 15, display: 'flex', alignItems: 'center', gap: 6 }}>
              <span>⚖️</span> Queue Status
            </div>
            <p style={{ fontSize: 13, color: 'var(--color-text-muted)', margin: '4px 0 0' }}>
              Pending questions must satisfy difficulty ratios and syllabus criteria before approval.
            </p>
          </div>
          <div style={{ background: 'var(--color-warning-light)', color: 'var(--color-warning)', fontWeight: 700, padding: '8px 18px', borderRadius: 8, fontSize: 14 }}>
            {questions.length} Items Awaiting Review
          </div>
        </div>
      </div>

      {loading ? (
        <p style={{ padding: 40, textAlign: 'center', color: 'var(--color-text-muted)' }}>Loading pending approvals...</p>
      ) : questions.length === 0 ? (
        <div className="card" style={{ padding: 40, textAlign: 'center' }}>
          <div className="empty-state" style={{ color: 'var(--color-text-muted)', fontSize: 14 }}>
            🎉 All caught up! No questions waiting in the moderation queue.
          </div>
        </div>
      ) : (
        <div className="grid grid-2">
          {questions.map((q) => {
            const isAI = q.description?.includes('Generated for subject:') || q.description?.includes('difficulty)');
            return (
              <div
                className="card"
                key={q._id}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 12,
                  borderLeft: isAI ? '4px solid #a855f7' : '1px solid var(--color-border)',
                  position: 'relative'
                }}
              >
                {/* Meta details */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span className={`badge badge-${q.difficulty?.toLowerCase()}`}>{q.difficulty}</span>
                  <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                    {isAI && (
                      <span className="badge" style={{ background: 'linear-gradient(135deg, #6366f1, #a855f7)', color: 'white', fontSize: 11 }}>
                        ✨ AI Generated
                      </span>
                    )}
                    <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-muted)', textTransform: 'uppercase' }}>
                      {q.questionType}
                    </span>
                  </div>
                </div>

                {/* Content */}
                <div style={{ flex: 1 }}>
                  <p style={{ fontWeight: 600, fontSize: 14, margin: '0 0 8px', color: 'var(--color-text)', lineHeight: 1.4 }}>
                    {q.title}
                  </p>
                  {q.description && (
                    <p style={{ fontSize: 12, color: 'var(--color-text-muted)', background: 'var(--color-bg)', padding: 8, borderRadius: 6, margin: '0 0 10px' }}>
                      {q.description}
                    </p>
                  )}
                  {q.options?.length > 0 && (
                    <ul style={{ fontSize: 13, color: 'var(--color-text-muted)', paddingLeft: 18, margin: '0 0 10px' }}>
                      {q.options.map((opt, i) => (
                        <li key={i} style={{ marginBottom: 4 }}>{opt}</li>
                      ))}
                    </ul>
                  )}
                  {q.correctAnswer && (
                    <p style={{ fontSize: 12, color: 'var(--color-success)', fontWeight: 600, margin: 0 }}>
                      ✔️ Correct Answer: <span style={{ fontWeight: 400, color: 'var(--color-text-muted)' }}>{q.correctAnswer}</span>
                    </p>
                  )}
                </div>

                {/* Extra metrics */}
                <div style={{ display: 'flex', justifyContent: 'space-between', borderTop: '1px solid var(--color-border)', paddingTop: 10, fontSize: 11, color: 'var(--color-text-muted)' }}>
                  <span>Marks: <strong>{q.marks}</strong> · Bloom: <strong>{q.bloomLevel}</strong></span>
                  <span>By: <strong>{q.createdBy?.name || 'Faculty'}</strong></span>
                </div>

                {/* Action buttons */}
                <div style={{ marginTop: 6, borderTop: '1px solid var(--color-border)', paddingTop: 12 }}>
                  {rejectingId === q._id ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                      <textarea
                        className="form-control"
                        placeholder="Provide feedback/reason for rejection..."
                        value={reason}
                        onChange={(e) => setReason(e.target.value)}
                        style={{ minHeight: 60 }}
                      />
                      <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
                        <button className="btn btn-secondary btn-sm" onClick={() => setRejectingId(null)}>
                          Cancel
                        </button>
                        <button className="btn btn-danger btn-sm" onClick={() => handleReject(q._id)}>
                          Confirm Reject
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
                      <button className="btn btn-secondary btn-sm" onClick={() => setRejectingId(q._id)}>
                        Reject
                      </button>
                      <button className="btn btn-success btn-sm" onClick={() => handleApprove(q._id)}>
                        Approve & Save
                      </button>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default Approvals;
